"""Builds assets/activity.svg from the GitHub API. Run by .github/workflows/activity.yml."""
import json, os, urllib.request, datetime as dt
from collections import Counter

USER = os.environ.get("GH_USER", "Sriram27102003")
TOKEN = os.environ.get("GITHUB_TOKEN", "")
OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "activity.svg")

PAPER="#F3F0E9"; INK="#1C1F1D"; SAGE="#476556"; DSAGE="#2E4238"; AMBER="#E0A526"; MUTED="#77736A"; LINE="#DCD6CA"; TRACK="#E6E1D7"
SERIF="Georgia, 'Times New Roman', serif"
MONO="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"

def get(url):
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json", "User-Agent": USER})
    if TOKEN: req.add_header("Authorization", f"Bearer {TOKEN}")
    with urllib.request.urlopen(req) as r: return json.load(r)

repos = [r for r in get(f"https://api.github.com/users/{USER}/repos?per_page=100&type=owner") if not r["fork"]]
langs = Counter()
for r in repos:
    for k, v in get(r["languages_url"]).items(): langs[k] += v

events = []
for page in (1, 2, 3):
    batch = get(f"https://api.github.com/users/{USER}/events/public?per_page=100&page={page}")
    events += batch
    if len(batch) < 100: break

now = dt.datetime.now(dt.timezone.utc)
cut = now - dt.timedelta(days=30)
recent = [e for e in events if dt.datetime.fromisoformat(e["created_at"].replace("Z", "+00:00")) >= cut]
commits = sum(len(e["payload"].get("commits", [])) for e in recent if e["type"] == "PushEvent")
touched = len({e["repo"]["name"] for e in recent})
prs = sum(1 for e in recent if e["type"] == "PullRequestEvent" and e["payload"].get("action") == "opened")
days = Counter(dt.datetime.fromisoformat(e["created_at"].replace("Z", "+00:00")).date() for e in recent)

W = 900
stats = [(str(commits), "commits"), (str(touched), "repos touched"), (str(prs), "PRs opened"), (str(len(repos)), "public repos")]
body = ""
for i, (n, label) in enumerate(stats):
    x = 36 + i * 212
    body += f'<text x="{x}" y="92" font-family="{SERIF}" font-size="40" fill="{INK}">{n}</text>'
    body += f'<text x="{x}" y="114" font-family="{MONO}" font-size="12" fill="{MUTED}">{label}</text>'

# 30-day strip: one cell per day, darker = more events
strip = ""
mx = max(days.values()) if days else 1
for i in range(30):
    d = (now - dt.timedelta(days=29 - i)).date()
    c = days.get(d, 0)
    fill = TRACK if c == 0 else (AMBER if c == mx else SAGE)
    op = 1 if c == 0 else 0.45 + 0.55 * c / mx
    strip += f'<rect x="{36 + i * 27.6:.1f}" y="140" width="22" height="22" rx="3" fill="{fill}" opacity="{op:.2f}"><title>{d}: {c} events</title></rect>'

total = sum(langs.values()) or 1
top = langs.most_common(5)
bars = ""
y = 212
for name, b in top:
    pct = b / total
    bars += f'<text x="36" y="{y + 12}" font-family="{MONO}" font-size="12.5" fill="{INK}">{name}</text>'
    bars += f'<rect x="200" y="{y}" width="600" height="14" rx="3" fill="{TRACK}"/>'
    bars += f'<rect x="200" y="{y}" width="{max(4, 600 * pct):.1f}" height="14" rx="3" fill="{SAGE}"/>'
    bars += f'<text x="864" y="{y + 12}" text-anchor="end" font-family="{MONO}" font-size="12.5" fill="{MUTED}">{pct * 100:.0f}%</text>'
    y += 28
H = y + 34

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" role="img" aria-label="GitHub activity, last 30 days">
<rect x="1" y="1" width="{W-2}" height="{H-2}" rx="12" fill="{PAPER}" stroke="{LINE}" stroke-width="1.5"/>
<text x="36" y="40" font-family="{SERIF}" font-size="17" fill="{SAGE}">Last 30 days</text>
<text x="{W-36}" y="40" text-anchor="end" font-family="{MONO}" font-size="11.5" fill="{MUTED}">updated {now:%d %b %Y}</text>
{body}{strip}
<text x="36" y="196" font-family="{SERIF}" font-size="17" fill="{SAGE}">Languages across my repos</text>
{bars}
<text x="36" y="{H-16}" font-family="{MONO}" font-size="11" fill="{MUTED}">public events only · generated by scripts/activity.py</text>
</svg>'''
open(OUT, "w").write(svg)
print(f"wrote {OUT}: {commits} commits, {touched} repos, {len(top)} languages")
